// A model that cas country name, country flag, country capitol
enum Difficulty {
  easy,
  normal,
  hard,
}

class Country {
  String name;
  String flagPath;
  String capital;
  Difficulty difficulty;
  double latitude;
  String? nationalAnimal;

  Country({
    required this.name,
    required this.flagPath,
    required this.capital,
    required this.difficulty,
    required this.latitude,
    this.nationalAnimal,
  });
}

List<Country> northAmericaCountries = [
  Country(
    name: 'Antigua and Barbuda',
    flagPath: 'assets/flags/naflags/antigua_and_barbuda_flag.png',
    capital: "Saint John's",
    difficulty: Difficulty.normal,
    latitude: 17.118,
    nationalAnimal: null,
  ),
  Country(
    name: 'Bahamas',
    flagPath: 'assets/flags/naflags/bahamas_flag.png',
    capital: 'Nassau',
    difficulty: Difficulty.easy,
    latitude: 25.034,
    nationalAnimal: null,
  ),
  Country(
    name: 'Barbados',
    flagPath: 'assets/flags/naflags/barbados_flag.png',
    capital: 'Bridgetown',
    difficulty: Difficulty.normal,
    latitude: 13.097,
    nationalAnimal: null,
  ),
  Country(
    name: 'Belize',
    flagPath: 'assets/flags/naflags/belize_flag.png',
    capital: 'Belmopan',
    difficulty: Difficulty.normal,
    latitude: 17.189,
    nationalAnimal: null,
  ),
  Country(
    name: 'Canada',
    flagPath: 'assets/flags/naflags/canada_flag.png',
    capital: 'Ottawa',
    difficulty: Difficulty.hard,
    latitude: 45.421,
    nationalAnimal: 'Beaver',
  ),
  Country(
    name: 'Costa Rica',
    flagPath: 'assets/flags/naflags/costa_rica_flag.png',
    capital: 'San Jose',
    difficulty: Difficulty.easy,
    latitude: 9.928,
    nationalAnimal: 'White-tailed deer',
  ),
  Country(
    name: 'Cuba',
    flagPath: 'assets/flags/naflags/cuba_flag.png',
    capital: 'Havana',
    difficulty: Difficulty.normal,
    latitude: 23.113,
    nationalAnimal: 'Cuban crocodile',
  ),
  Country(
    name: 'Dominica',
    flagPath: 'assets/flags/naflags/dominica_flag.png',
    capital: 'Roseau',
    difficulty: Difficulty.easy,
    latitude: 15.415,
    nationalAnimal: 'Sisserou parrot',
  ),
  Country(
    name: 'Dominican Republic',
    flagPath: 'assets/flags/naflags/dominican_republic_flag.png',
    capital: 'Santo Domingo',
    difficulty: Difficulty.easy,
    latitude: 18.735,
    nationalAnimal: 'Palmchat',
  ),
  Country(
    name: 'El Salvador',
    flagPath: 'assets/flags/naflags/el_salvador_flag.png',
    capital: 'San Salvador',
    difficulty: Difficulty.easy,
    latitude: 13.692,
    nationalAnimal: null,
  ),
  Country(
    name: 'Grenada',
    flagPath: 'assets/flags/naflags/grenada_flag.png',
    capital: "Saint George's",
    difficulty: Difficulty.normal,
    latitude: 12.057,
    nationalAnimal: 'Dove',
  ),
  Country(
    name: 'Guatemala',
    flagPath: 'assets/flags/naflags/guatemala_flag.png',
    capital: 'Guatemala City',
    difficulty: Difficulty.normal,
    latitude: 14.634,
    nationalAnimal: 'Quetzal',
  ),
  Country(
    name: 'Haiti',
    flagPath: 'assets/flags/naflags/haiti_flag.png',
    capital: 'Port-au-Prince',
    difficulty: Difficulty.easy,
    latitude: 18.594,
    nationalAnimal: 'Hispaniolan trogon',
  ),
  Country(
    name: 'Honduras',
    flagPath: 'assets/flags/naflags/honduras_flag.png',
    capital: 'Tegucigalpa',
    difficulty: Difficulty.easy,
    latitude: 14.058,
    nationalAnimal: 'White-tailed deer',
  ),
  Country(
    name: 'Jamaica',
    flagPath: 'assets/flags/naflags/jamaica_flag.png',
    capital: 'Kingston',
    difficulty: Difficulty.easy,
    latitude: 18.017,
    nationalAnimal: 'Red-billed streamertail',
  ),
  Country(
    name: 'Mexico',
    flagPath: 'assets/flags/naflags/mexico_flag.png',
    capital: 'Mexico City',
    difficulty: Difficulty.normal,
    latitude: 19.432,
    nationalAnimal: 'Golden eagle',
  ),
  Country(
    name: 'Nicaragua',
    flagPath: 'assets/flags/naflags/nicaragua_flag.png',
    capital: 'Managua',
    difficulty: Difficulty.easy,
    latitude: 12.114,
    nationalAnimal: 'Turquoise-browed motmot',
  ),
  Country(
    name: 'Panama',
    flagPath: 'assets/flags/naflags/panama_flag.png',
    capital: 'Panama City',
    difficulty: Difficulty.easy,
    latitude: 8.982,
    nationalAnimal: 'Harpy eagle',
  ),
  Country(
    name: 'Saint Kitts and Nevis',
    flagPath: 'assets/flags/naflags/saint_kitts_and_nevis_flag.png',
    capital: 'Basseterre',
    difficulty: Difficulty.easy,
    latitude: 17.302,
    nationalAnimal: 'Green vervet monkey',
  ),
  Country(
    name: 'Saint Lucia',
    flagPath: 'assets/flags/naflags/saint_lucia_flag.png',
    capital: 'Castries',
    difficulty: Difficulty.easy,
    latitude: 13.909,
    nationalAnimal: 'Saint Lucia amazon',
  ),
  Country(
    name: 'Saint Vincent and the Grenadines',
    flagPath: 'assets/flags/naflags/saint_vincent_and_the_grenadines_flag.png',
    capital: 'Kingstown',
    difficulty: Difficulty.easy,
    latitude: 13.253,
    nationalAnimal: 'Saint Vincent amazon',
  ),
  Country(
    name: 'Trinidad and Tobago',
    flagPath: 'assets/flags/naflags/trinidad_and_tobago_flag.png',
    capital: 'Port of Spain',
    difficulty: Difficulty.easy,
    latitude: 10.691,
    nationalAnimal: 'Scarlet ibis',
  ),
  Country(
    name: 'United States of America',
    flagPath: 'assets/flags/naflags/united_states_of_america_flag.png',
    capital: 'Washington, D.C.',
    difficulty: Difficulty.hard,
    latitude: 38.907,
    nationalAnimal: 'Bald eagle',
  ),
];

List<Country> southAmericaCountries = [
  Country(
    name: 'Brazil',
    flagPath: 'assets/flags/saflags/brazil_flag.png',
    capital: 'Brasília',
    difficulty: Difficulty.easy,
    latitude: -15.780,
    nationalAnimal: 'Jaguar',
  ),
  Country(
    name: 'Colombia',
    flagPath: 'assets/flags/saflags/colombia_flag.png',
    capital: 'Bogotá',
    difficulty: Difficulty.easy,
    latitude: 4.711,
    nationalAnimal: 'Andean condor',
  ),
  Country(
    name: 'Argentina',
    flagPath: 'assets/flags/saflags/argentina_flag.png',
    capital: 'Buenos Aires',
    difficulty: Difficulty.easy,
    latitude: -34.609,
    nationalAnimal: 'Andean condor',
  ),
  Country(
    name: 'Peru',
    flagPath: 'assets/flags/saflags/peru_flag.png',
    capital: 'Lima',
    difficulty: Difficulty.easy,
    latitude: -12.046,
    nationalAnimal: 'Andean cock-of-the-rock',
  ),
  Country(
    name: 'Venezuela',
    flagPath: 'assets/flags/saflags/venezuela_flag.png',
    capital: 'Caracas',
    difficulty: Difficulty.easy,
    latitude: 10.480,
    nationalAnimal: 'Venezuelan troupial',
  ),
  Country(
    name: 'Chile',
    flagPath: 'assets/flags/saflags/chile_flag.png',
    capital: 'Santiago',
    difficulty: Difficulty.easy,
    latitude: -33.448,
    nationalAnimal: 'Huemul',
  ),
  Country(
    name: 'Ecuador',
    flagPath: 'assets/flags/saflags/ecuador_flag.png',
    capital: 'Quito',
    difficulty: Difficulty.easy,
    latitude: -0.229,
    nationalAnimal: 'Andean condor',
  ),
  Country(
    name: 'Bolivia',
    flagPath: 'assets/flags/saflags/bolivia_flag.png',
    capital: 'La Paz',
    difficulty: Difficulty.easy,
    latitude: -16.500,
    nationalAnimal: 'Llama',
  ),
  Country(
    name: 'Paraguay',
    flagPath: 'assets/flags/saflags/paraguay_flag.png',
    capital: 'Asunción',
    difficulty: Difficulty.easy,
    latitude: -25.263,
    nationalAnimal: 'Jaguar',
  ),
  Country(
    name: 'Uruguay',
    flagPath: 'assets/flags/saflags/uruguay_flag.png',
    capital: 'Montevideo',
    difficulty: Difficulty.easy,
    latitude: -34.903,
    nationalAnimal: 'South American tapir',
  ),
  Country(
    name: 'Guyana',
    flagPath: 'assets/flags/saflags/guyana_flag.png',
    capital: 'Georgetown',
    difficulty: Difficulty.easy,
    latitude: 6.801,
    nationalAnimal: 'Jaguar',
  ),
  Country(
    name: 'Suriname',
    flagPath: 'assets/flags/saflags/suriname_flag.png',
    capital: 'Paramaribo',
    difficulty: Difficulty.easy,
    latitude: 5.852,
    nationalAnimal: 'Surinamese jaguar',
  ),
];

List<Country> africanCountries = [
  Country(
    name: 'Algeria',
    flagPath: 'assets/flags/africaflags/algeria_flag.png',
    capital: 'Algiers',
    difficulty: Difficulty.normal,
    latitude: 28.033,
    nationalAnimal: null,
  ),
  Country(
    name: 'Angola',
    flagPath: 'assets/flags/africaflags/angola_flag.png',
    capital: 'Luanda',
    difficulty: Difficulty.normal,
    latitude: -8.839,
    nationalAnimal: 'Black-crowned crane',
  ),
  Country(
    name: 'Benin',
    flagPath: 'assets/flags/africaflags/benin_flag.png',
    capital: 'Porto-Novo',
    difficulty: Difficulty.easy,
    latitude: 6.335,
    nationalAnimal: null,
  ),
  Country(
    name: 'Botswana',
    flagPath: 'assets/flags/africaflags/botswana_flag.png',
    capital: 'Gaborone',
    difficulty: Difficulty.normal,
    latitude: -24.658,
    nationalAnimal: 'Zebra',
  ),
  Country(
    name: 'Burkina Faso',
    flagPath: 'assets/flags/africaflags/burkina_faso_flag.png',
    capital: 'Ouagadougou',
    difficulty: Difficulty.easy,
    latitude: 12.238,
    nationalAnimal: 'N/A',
  ),
  Country(
    name: 'Burundi',
    flagPath: 'assets/flags/africaflags/burundi_flag.png',
    capital: 'Bujumbura',
    difficulty: Difficulty.easy,
    latitude: -3.373,
    nationalAnimal: null,
  ),
  Country(
    name: 'Cabo Verde',
    flagPath: 'assets/flags/africaflags/cabo_verde_flag.png',
    capital: 'Praia',
    difficulty: Difficulty.easy,
    latitude: 14.916,
    nationalAnimal: null,
  ),
  Country(
    name: 'Cameroon',
    flagPath: 'assets/flags/africaflags/cameroon_flag.png',
    capital: 'Yaoundé',
    difficulty: Difficulty.normal,
    latitude: 3.848,
    nationalAnimal: 'Lion',
  ),
  Country(
    name: 'Central African Republic',
    flagPath: 'assets/flags/africaflags/central_african_republic_flag.png',
    capital: 'Bangui',
    difficulty: Difficulty.normal,
    latitude: 4.394,
    nationalAnimal: null,
  ),
  Country(
    name: 'Chad',
    flagPath: 'assets/flags/africaflags/chad_flag.png',
    capital: "N'Djamena",
    difficulty: Difficulty.normal,
    latitude: 12.105,
    nationalAnimal: 'African fish eagle',
  ),
  Country(
    name: 'Comoros',
    flagPath: 'assets/flags/africaflags/comoros_flag.png',
    capital: 'Moroni',
    difficulty: Difficulty.easy,
    latitude: -11.875,
    nationalAnimal: 'Coelacanth',
  ),
  Country(
    name: 'Democratic Republic of the Congo',
    flagPath:
        'assets/flags/africaflags/democratic_republic_of_the_congo_flag.png',
    capital: 'Kinshasa',
    difficulty: Difficulty.normal,
    latitude: -4.038,
    nationalAnimal: null,
  ),
  Country(
    name: 'Republic of the Congo',
    flagPath: 'assets/flags/africaflags/republic_of_the_congo_flag.png',
    capital: 'Brazzaville',
    difficulty: Difficulty.easy,
    latitude: -4.263,
    nationalAnimal: null,
  ),
  Country(
    name: 'Djibouti',
    flagPath: 'assets/flags/africaflags/djibouti_flag.png',
    capital: 'Djibouti',
    difficulty: Difficulty.easy,
    latitude: 11.825,
    nationalAnimal: null,
  ),
  Country(
    name: 'Egypt',
    flagPath: 'assets/flags/africaflags/egypt_flag.png',
    capital: 'Cairo',
    difficulty: Difficulty.normal,
    latitude: 26.820,
    nationalAnimal: null,
  ),
  Country(
    name: 'Equatorial Guinea',
    flagPath: 'assets/flags/africaflags/equatorial_guinea_flag.png',
    capital: 'Malabo',
    difficulty: Difficulty.normal,
    latitude: 3.752,
    nationalAnimal: null,
  ),
  Country(
    name: 'Eritrea',
    flagPath: 'assets/flags/africaflags/eritrea_flag.png',
    capital: 'Asmara',
    difficulty: Difficulty.normal,
    latitude: 15.322,
    nationalAnimal: null,
  ),
  Country(
    name: 'Eswatini',
    flagPath: 'assets/flags/africaflags/eswatini_flag.png',
    capital: 'Mbabane',
    difficulty: Difficulty.easy,
    latitude: -26.305,
    nationalAnimal: null,
  ),
  Country(
    name: 'Ethiopia',
    flagPath: 'assets/flags/africaflags/ethiopia_flag.png',
    capital: 'Addis Ababa',
    difficulty: Difficulty.normal,
    latitude: 9.145,
    nationalAnimal: null,
  ),
  Country(
    name: 'Gabon',
    flagPath: 'assets/flags/africaflags/gabon_flag.png',
    capital: 'Libreville',
    difficulty: Difficulty.normal,
    latitude: 0.392,
    nationalAnimal: null,
  ),
  Country(
    name: 'Gambia',
    flagPath: 'assets/flags/africaflags/gambia_flag.png',
    capital: 'Banjul',
    difficulty: Difficulty.easy,
    latitude: 13.446,
    nationalAnimal: null,
  ),
  Country(
    name: 'Ghana',
    flagPath: 'assets/flags/africaflags/ghana_flag.png',
    capital: 'Accra',
    difficulty: Difficulty.easy,
    latitude: 5.603,
    nationalAnimal: 'Golden eagle',
  ),
  Country(
    name: 'Guinea',
    flagPath: 'assets/flags/africaflags/guinea_flag.png',
    capital: 'Conakry',
    difficulty: Difficulty.easy,
    latitude: 9.945,
    nationalAnimal: null,
  ),
  Country(
    name: 'Guinea-Bissau',
    flagPath: 'assets/flags/africaflags/guinea_bissau_flag.png',
    capital: 'Bissau',
    difficulty: Difficulty.easy,
    latitude: 11.803,
    nationalAnimal: null,
  ),
  Country(
    name: 'Ivory Coast',
    flagPath: 'assets/flags/africaflags/ivory_coast_flag.png',
    capital: 'Yamoussoukro',
    difficulty: Difficulty.easy,
    latitude: 7.540,
    nationalAnimal: 'Elephant',
  ),
  Country(
    name: 'Kenya',
    flagPath: 'assets/flags/africaflags/kenya_flag.png',
    capital: 'Nairobi',
    difficulty: Difficulty.easy,
    latitude: -1.286,
    nationalAnimal: 'Lion',
  ),
  Country(
    name: 'Lesotho',
    flagPath: 'assets/flags/africaflags/lesotho_flag.png',
    capital: 'Maseru',
    difficulty: Difficulty.easy,
    latitude: -29.610,
    nationalAnimal: null,
  ),
  Country(
    name: 'Liberia',
    flagPath: 'assets/flags/africaflags/liberia_flag.png',
    capital: 'Monrovia',
    difficulty: Difficulty.easy,
    latitude: 6.315,
    nationalAnimal: 'Giant snail',
  ),
  Country(
    name: 'Libya',
    flagPath: 'assets/flags/africaflags/libya_flag.png',
    capital: 'Tripoli',
    difficulty: Difficulty.normal,
    latitude: 32.887,
    nationalAnimal: null,
  ),
  Country(
    name: 'Madagascar',
    flagPath: 'assets/flags/africaflags/madagascar_flag.png',
    capital: 'Antananarivo',
    difficulty: Difficulty.easy,
    latitude: -18.879,
    nationalAnimal: 'Ring-tailed lemur',
  ),
  Country(
    name: 'Malawi',
    flagPath: 'assets/flags/africaflags/malawi_flag.png',
    capital: 'Lilongwe',
    difficulty: Difficulty.easy,
    latitude: -13.254,
    nationalAnimal: null,
  ),
  Country(
    name: 'Mali',
    flagPath: 'assets/flags/africaflags/mali_flag.png',
    capital: 'Bamako',
    difficulty: Difficulty.easy,
    latitude: 17.570,
    nationalAnimal: 'Giraffe',
  ),
  Country(
    name: 'Mauritania',
    flagPath: 'assets/flags/africaflags/mauritania_flag.png',
    capital: 'Nouakchott',
    difficulty: Difficulty.easy,
    latitude: 18.099,
    nationalAnimal: null,
  ),
  Country(
    name: 'Mauritius',
    flagPath: 'assets/flags/africaflags/mauritius_flag.png',
    capital: 'Port Louis',
    difficulty: Difficulty.easy,
    latitude: -20.160,
    nationalAnimal: 'Dodo',
  ),
  Country(
    name: 'Morocco',
    flagPath: 'assets/flags/africaflags/morocco_flag.png',
    capital: 'Rabat',
    difficulty: Difficulty.normal,
    latitude: 33.971,
    nationalAnimal: null,
  ),
  Country(
    name: 'Mozambique',
    flagPath: 'assets/flags/africaflags/mozambique_flag.png',
    capital: 'Maputo',
    difficulty: Difficulty.easy,
    latitude: -25.966,
    nationalAnimal: null,
  ),
  Country(
    name: 'Namibia',
    flagPath: 'assets/flags/africaflags/namibia_flag.png',
    capital: 'Windhoek',
    difficulty: Difficulty.easy,
    latitude: -22.559,
    nationalAnimal: null,
  ),
  Country(
    name: 'Niger',
    flagPath: 'assets/flags/africaflags/niger_flag.png',
    capital: 'Niamey',
    difficulty: Difficulty.easy,
    latitude: 13.512,
    nationalAnimal: null,
  ),
  Country(
    name: 'Nigeria',
    flagPath: 'assets/flags/africaflags/nigeria_flag.png',
    capital: 'Abuja',
    difficulty: Difficulty.easy,
    latitude: 9.072,
    nationalAnimal: 'Eagle',
  ),
  Country(
    name: 'Rwanda',
    flagPath: 'assets/flags/africaflags/rwanda_flag.png',
    capital: 'Kigali',
    difficulty: Difficulty.easy,
    latitude: -1.944,
    nationalAnimal: null,
  ),
  Country(
    name: 'São Tomé and Príncipe',
    flagPath: 'assets/flags/africaflags/sao_tome_and_principe_flag.png',
    capital: 'São Tomé',
    difficulty: Difficulty.easy,
    latitude: 0.336,
    nationalAnimal: null,
  ),
  Country(
    name: 'Senegal',
    flagPath: 'assets/flags/africaflags/senegal_flag.png',
    capital: 'Dakar',
    difficulty: Difficulty.easy,
    latitude: 14.695,
    nationalAnimal: null,
  ),
  Country(
    name: 'Seychelles',
    flagPath: 'assets/flags/africaflags/seychelles_flag.png',
    capital: 'Victoria',
    difficulty: Difficulty.easy,
    latitude: -4.679,
    nationalAnimal: null,
  ),
  Country(
    name: 'Sierra Leone',
    flagPath: 'assets/flags/africaflags/sierra_leone_flag.png',
    capital: 'Freetown',
    difficulty: Difficulty.easy,
    latitude: 8.465,
    nationalAnimal: null,
  ),
  Country(
    name: 'Somalia',
    flagPath: 'assets/flags/africaflags/somalia_flag.png',
    capital: 'Mogadishu',
    difficulty: Difficulty.normal,
    latitude: 2.046,
    nationalAnimal: null,
  ),
  Country(
    name: 'South Africa',
    flagPath: 'assets/flags/africaflags/south_africa_flag.png',
    capital: 'Pretoria',
    difficulty: Difficulty.easy,
    latitude: -25.746,
    nationalAnimal: 'Springbok',
  ),
  Country(
    name: 'South Sudan',
    flagPath: 'assets/flags/africaflags/south_sudan_flag.png',
    capital: 'Juba',
    difficulty: Difficulty.normal,
    latitude: 4.859,
    nationalAnimal: null,
  ),
  Country(
    name: 'Sudan',
    flagPath: 'assets/flags/africaflags/sudan_flag.png',
    capital: 'Khartoum',
    difficulty: Difficulty.normal,
    latitude: 15.593,
    nationalAnimal: null,
  ),
  Country(
    name: 'Tanzania',
    flagPath: 'assets/flags/africaflags/tanzania_flag.png',
    capital: 'Dodoma',
    difficulty: Difficulty.easy,
    latitude: -6.369,
    nationalAnimal: 'Giraffe',
  ),
  Country(
    name: 'Togo',
    flagPath: 'assets/flags/africaflags/togo_flag.png',
    capital: 'Lomé',
    difficulty: Difficulty.easy,
    latitude: 6.131,
    nationalAnimal: null,
  ),
  Country(
    name: 'Tunisia',
    flagPath: 'assets/flags/africaflags/tunisia_flag.png',
    capital: 'Tunis',
    difficulty: Difficulty.normal,
    latitude: 36.806,
    nationalAnimal: null,
  ),
  Country(
    name: 'Uganda',
    flagPath: 'assets/flags/africaflags/uganda_flag.png',
    capital: 'Kampala',
    difficulty: Difficulty.easy,
    latitude: 0.347,
    nationalAnimal: 'Grey crowned crane',
  ),
  Country(
    name: 'Zambia',
    flagPath: 'assets/flags/africaflags/zambia_flag.png',
    capital: 'Lusaka',
    difficulty: Difficulty.easy,
    latitude: -15.387,
    nationalAnimal: 'African fish eagle',
  ),
  Country(
    name: 'Zimbabwe',
    flagPath: 'assets/flags/africaflags/zimbabwe_flag.png',
    capital: 'Harare',
    difficulty: Difficulty.easy,
    latitude: -17.825,
    nationalAnimal: 'Sable antelope',
  ),
];

List<Country> oceaniaCountries = [
  Country(
    name: 'Australia',
    flagPath: 'assets/flags/oceaniaflags/australia_flag.png',
    capital: 'Canberra',
    difficulty: Difficulty.easy,
    latitude: -35.308,
    nationalAnimal: 'Red kangaroo',
  ),
  Country(
    name: 'Fiji',
    flagPath: 'assets/flags/oceaniaflags/fiji_flag.png',
    capital: 'Suva',
    difficulty: Difficulty.easy,
    latitude: -18.141,
    nationalAnimal: 'Fiji banded iguana',
  ),
  Country(
    name: 'Kiribati',
    flagPath: 'assets/flags/oceaniaflags/kiribati_flag.png',
    capital: 'Tarawa',
    difficulty: Difficulty.easy,
    latitude: 1.870,
    nationalAnimal: null,
  ),
  Country(
    name: 'Marshall Islands',
    flagPath: 'assets/flags/oceaniaflags/marshall_islands_flag.png',
    capital: 'Majuro',
    difficulty: Difficulty.easy,
    latitude: 7.116,
    nationalAnimal: null,
  ),
  Country(
    name: 'Micronesia',
    flagPath: 'assets/flags/oceaniaflags/micronesia_flag.png',
    capital: 'Palikir',
    difficulty: Difficulty.easy,
    latitude: 6.924,
    nationalAnimal: null,
  ),
  Country(
    name: 'Nauru',
    flagPath: 'assets/flags/oceaniaflags/nauru_flag.png',
    capital: 'Yaren',
    difficulty: Difficulty.easy,
    latitude: -0.540,
    nationalAnimal: null,
  ),
  Country(
    name: 'New Zealand',
    flagPath: 'assets/flags/oceaniaflags/new_zealand_flag.png',
    capital: 'Wellington',
    difficulty: Difficulty.easy,
    latitude: -41.290,
    nationalAnimal: 'Kiwi',
  ),
  Country(
    name: 'Palau',
    flagPath: 'assets/flags/oceaniaflags/palau_flag.png',
    capital: 'Ngerulmud',
    difficulty: Difficulty.easy,
    latitude: 7.500,
    nationalAnimal: null,
  ),
  Country(
    name: 'Papua New Guinea',
    flagPath: 'assets/flags/oceaniaflags/papua_new_guinea_flag.png',
    capital: 'Port Moresby',
    difficulty: Difficulty.easy,
    latitude: -9.444,
    nationalAnimal: null,
  ),
  Country(
    name: 'Samoa',
    flagPath: 'assets/flags/oceaniaflags/samoa_flag.png',
    capital: 'Apia',
    difficulty: Difficulty.easy,
    latitude: -13.759,
    nationalAnimal: null,
  ),
  Country(
    name: 'Solomon Islands',
    flagPath: 'assets/flags/oceaniaflags/solomon_islands_flag.png',
    capital: 'Honiara',
    difficulty: Difficulty.easy,
    latitude: -9.433,
    nationalAnimal: null,
  ),
  Country(
    name: 'Tonga',
    flagPath: 'assets/flags/oceaniaflags/tonga_flag.png',
    capital: 'Nuku\'alofa',
    difficulty: Difficulty.easy,
    latitude: -21.136,
    nationalAnimal: null,
  ),
  Country(
    name: 'Tuvalu',
    flagPath: 'assets/flags/oceaniaflags/tuvalu_flag.png',
    capital: 'Funafuti',
    difficulty: Difficulty.easy,
    latitude: -8.525,
    nationalAnimal: null,
  ),
  Country(
    name: 'Vanuatu',
    flagPath: 'assets/flags/oceaniaflags/vanuatu_flag.png',
    capital: 'Port Vila',
    difficulty: Difficulty.easy,
    latitude: -17.740,
    nationalAnimal: null,
  ),
];

List<Country> europeanCountries = [
  Country(
    name: 'Denmark',
    flagPath: 'assets/flags/euflags/denmark_flag.png',
    capital: 'Copenhagen',
    difficulty: Difficulty.easy,
    latitude: 55.676,
    nationalAnimal: 'Mute swan',
  ),
  Country(
    name: 'Estonia',
    flagPath: 'assets/flags/euflags/estonia_flag.png',
    capital: 'Tallinn',
    difficulty: Difficulty.easy,
    latitude: 59.437,
    nationalAnimal: 'Barn swallow',
  ),
  Country(
    name: 'Finland',
    flagPath: 'assets/flags/euflags/finland_flag.png',
    capital: 'Helsinki',
    difficulty: Difficulty.easy,
    latitude: 60.169,
    nationalAnimal: 'Brown bear',
  ),
  Country(
    name: 'Iceland',
    flagPath: 'assets/flags/euflags/iceland_flag.png',
    capital: 'Reykjavik',
    difficulty: Difficulty.easy,
    latitude: 64.146,
    nationalAnimal: 'Gyrfalcon',
  ),
  Country(
    name: 'Ireland',
    flagPath: 'assets/flags/euflags/ireland_flag.png',
    capital: 'Dublin',
    difficulty: Difficulty.easy,
    latitude: 53.349,
    nationalAnimal: 'Red deer',
  ),
  Country(
    name: 'Latvia',
    flagPath: 'assets/flags/euflags/latvia_flag.png',
    capital: 'Riga',
    difficulty: Difficulty.easy,
    latitude: 56.949,
    nationalAnimal: 'White wagtail',
  ),
  Country(
    name: 'Lithuania',
    flagPath: 'assets/flags/euflags/lithuania_flag.png',
    capital: 'Vilnius',
    difficulty: Difficulty.easy,
    latitude: 54.687,
    nationalAnimal: 'White stork',
  ),
  Country(
    name: 'Norway',
    flagPath: 'assets/flags/euflags/norway_flag.png',
    capital: 'Oslo',
    difficulty: Difficulty.easy,
    latitude: 59.913,
    nationalAnimal: 'Elk',
  ),
  Country(
    name: 'Sweden',
    flagPath: 'assets/flags/euflags/sweden_flag.png',
    capital: 'Stockholm',
    difficulty: Difficulty.easy,
    latitude: 59.329,
    nationalAnimal: 'Moose',
  ),
  Country(
    name: 'United Kingdom',
    flagPath: 'assets/flags/euflags/united_kingdom_flag.png',
    capital: 'London',
    difficulty: Difficulty.easy,
    latitude: 51.507,
    nationalAnimal: 'Lion',
  ),
  Country(
    name: 'Albania',
    flagPath: 'assets/flags/euflags/albania_flag.png',
    capital: 'Tirana',
    difficulty: Difficulty.easy,
    latitude: 41.327,
    nationalAnimal: 'Golden eagle',
  ),
  Country(
    name: 'Andorra',
    flagPath: 'assets/flags/euflags/andorra_flag.png',
    capital: 'Andorra la Vella',
    difficulty: Difficulty.easy,
    latitude: 42.506,
    nationalAnimal: 'Pyrenean chamois',
  ),
  Country(
    name: 'Bosnia and Herzegovina',
    flagPath: 'assets/flags/euflags/bosnia_and_herzegovina_flag.png',
    capital: 'Sarajevo',
    difficulty: Difficulty.easy,
    latitude: 43.856,
    nationalAnimal: 'Bosnian Coarse-Haired Hound',
  ),
  Country(
    name: 'Croatia',
    flagPath: 'assets/flags/euflags/croatia_flag.png',
    capital: 'Zagreb',
    difficulty: Difficulty.easy,
    latitude: 45.815,
    nationalAnimal: 'Dalmatian dog',
  ),
  Country(
    name: 'Cyprus',
    flagPath: 'assets/flags/euflags/cyprus_flag.png',
    capital: 'Nicosia',
    difficulty: Difficulty.easy,
    latitude: 35.185,
    nationalAnimal: 'Cypriot mouflon',
  ),
  Country(
    name: 'Greece',
    flagPath: 'assets/flags/euflags/greece_flag.png',
    capital: 'Athens',
    difficulty: Difficulty.easy,
    latitude: 37.983,
    nationalAnimal: 'Dolphin',
  ),
  Country(
    name: 'Italy',
    flagPath: 'assets/flags/euflags/italy_flag.png',
    capital: 'Rome',
    difficulty: Difficulty.easy,
    latitude: 41.902,
    nationalAnimal: 'Italian wolf',
  ),
  Country(
    name: 'Malta',
    flagPath: 'assets/flags/euflags/malta_flag.png',
    capital: 'Valletta',
    difficulty: Difficulty.easy,
    latitude: 35.897,
    nationalAnimal: 'Maltese tiger moth',
  ),
  Country(
    name: 'Montenegro',
    flagPath: 'assets/flags/euflags/montenegro_flag.png',
    capital: 'Podgorica',
    difficulty: Difficulty.easy,
    latitude: 42.708,
    nationalAnimal: 'Golden eagle',
  ),
  Country(
    name: 'North Macedonia',
    flagPath: 'assets/flags/euflags/north_macedonia_flag.png',
    capital: 'Skopje',
    difficulty: Difficulty.easy,
    latitude: 41.997,
    nationalAnimal: 'Macedonian lynx',
  ),
  Country(
    name: 'Portugal',
    flagPath: 'assets/flags/euflags/portugal_flag.png',
    capital: 'Lisbon',
    difficulty: Difficulty.easy,
    latitude: 38.722,
    nationalAnimal: 'Iberian wolf',
  ),
  Country(
    name: 'San Marino',
    flagPath: 'assets/flags/euflags/san_marino_flag.png',
    capital: 'San Marino',
    difficulty: Difficulty.easy,
    latitude: 43.936,
    nationalAnimal: 'Mount Titan salamander',
  ),
  Country(
    name: 'Serbia',
    flagPath: 'assets/flags/euflags/serbia_flag.png',
    capital: 'Belgrade',
    difficulty: Difficulty.easy,
    latitude: 44.786,
    nationalAnimal: 'White eagle',
  ),
  Country(
    name: 'Slovenia',
    flagPath: 'assets/flags/euflags/slovenia_flag.png',
    capital: 'Ljubljana',
    difficulty: Difficulty.easy,
    latitude: 46.056,
    nationalAnimal: 'Lynx',
  ),
  Country(
    name: 'Spain',
    flagPath: 'assets/flags/euflags/spain_flag.png',
    capital: 'Madrid',
    difficulty: Difficulty.easy,
    latitude: 40.416,
    nationalAnimal: 'Bull',
  ),
  Country(
    name: 'Turkey',
    flagPath: 'assets/flags/euflags/turkey_flag.png',
    capital: 'Ankara',
    difficulty: Difficulty.easy,
    latitude: 39.933,
    nationalAnimal: 'Grey wolf',
  ),
  Country(
    name: 'Vatican City',
    flagPath: 'assets/flags/euflags/vatican_city_flag.png',
    capital: 'Vatican City',
    difficulty: Difficulty.easy,
    latitude: 41.902,
    nationalAnimal: 'Swiss Guard',
  ),
  Country(
    name: 'Belarus',
    flagPath: 'assets/flags/euflags/belarus_flag.png',
    capital: 'Minsk',
    difficulty: Difficulty.easy,
    latitude: 53.904,
    nationalAnimal: 'European bison',
  ),
  Country(
    name: 'Bulgaria',
    flagPath: 'assets/flags/euflags/bulgaria_flag.png',
    capital: 'Sofia',
    difficulty: Difficulty.easy,
    latitude: 42.697,
    nationalAnimal: 'Lion',
  ),
  Country(
    name: 'Czech Republic',
    flagPath: 'assets/flags/euflags/czech_republic_flag.png',
    capital: 'Prague',
    difficulty: Difficulty.easy,
    latitude: 50.075,
    nationalAnimal: 'Double-tailed lion',
  ),
  Country(
    name: 'Hungary',
    flagPath: 'assets/flags/euflags/hungary_flag.png',
    capital: 'Budapest',
    difficulty: Difficulty.easy,
    latitude: 47.498,
    nationalAnimal: 'Turul',
  ),
  Country(
    name: 'Moldova',
    flagPath: 'assets/flags/euflags/moldova_flag.png',
    capital: 'Chisinau',
    difficulty: Difficulty.easy,
    latitude: 47.026,
    nationalAnimal: 'Aurochs',
  ),
  Country(
    name: 'Poland',
    flagPath: 'assets/flags/euflags/poland_flag.png',
    capital: 'Warsaw',
    difficulty: Difficulty.easy,
    latitude: 52.229,
    nationalAnimal: 'White-tailed eagle',
  ),
  Country(
    name: 'Romania',
    flagPath: 'assets/flags/euflags/romania_flag.png',
    capital: 'Bucharest',
    difficulty: Difficulty.easy,
    latitude: 44.439,
    nationalAnimal: 'Golden eagle',
  ),
  Country(
    name: 'Russia',
    flagPath: 'assets/flags/euflags/russia_flag.png',
    capital: 'Moscow',
    difficulty: Difficulty.easy,
    latitude: 55.751,
    nationalAnimal: 'Brown bear',
  ),
  Country(
    name: 'Slovakia',
    flagPath: 'assets/flags/euflags/slovakia_flag.png',
    capital: 'Bratislava',
    difficulty: Difficulty.easy,
    latitude: 48.148,
    nationalAnimal: 'Golden eagle',
  ),
  Country(
    name: 'Ukraine',
    flagPath: 'assets/flags/euflags/ukraine_flag.png',
    capital: 'Kyiv',
    difficulty: Difficulty.easy,
    latitude: 50.450,
    nationalAnimal: 'Grey wolf',
  ),
  Country(
    name: 'Austria',
    flagPath: 'assets/flags/euflags/austria_flag.png',
    capital: 'Vienna',
    difficulty: Difficulty.easy,
    latitude: 48.208,
    nationalAnimal: 'Eagle',
  ),
  Country(
    name: 'Belgium',
    flagPath: 'assets/flags/euflags/belgium_flag.png',
    capital: 'Brussels',
    difficulty: Difficulty.easy,
    latitude: 50.850,
    nationalAnimal: 'Lion',
  ),
  Country(
    name: 'France',
    flagPath: 'assets/flags/euflags/france_flag.png',
    capital: 'Paris',
    difficulty: Difficulty.easy,
    latitude: 48.856,
    nationalAnimal: 'Gallic rooster',
  ),
  Country(
    name: 'Germany',
    flagPath: 'assets/flags/euflags/germany_flag.png',
    capital: 'Berlin',
    difficulty: Difficulty.easy,
    latitude: 52.520,
    nationalAnimal: 'Bundesadler',
  ),
  Country(
    name: 'Liechtenstein',
    flagPath: 'assets/flags/euflags/liechtenstein_flag.png',
    capital: 'Vaduz',
    difficulty: Difficulty.easy,
    latitude: 47.141,
    nationalAnimal: 'Golden eagle',
  ),
  Country(
    name: 'Luxembourg',
    flagPath: 'assets/flags/euflags/luxembourg_flag.png',
    capital: 'Luxembourg City',
    difficulty: Difficulty.easy,
    latitude: 49.611,
    nationalAnimal: 'Lion',
  ),
  Country(
    name: 'Monaco',
    flagPath: 'assets/flags/euflags/monaco_flag.png',
    capital: 'Monaco',
    difficulty: Difficulty.easy,
    latitude: 43.738,
    nationalAnimal: 'Golden eagle',
  ),
  Country(
    name: 'Netherlands',
    flagPath: 'assets/flags/euflags/netherlands_flag.png',
    capital: 'Amsterdam',
    difficulty: Difficulty.easy,
    latitude: 52.366,
    nationalAnimal: 'Lion',
  ),
  Country(
    name: 'Switzerland',
    flagPath: 'assets/flags/euflags/switzerland_flag.png',
    capital: 'Bern',
    difficulty: Difficulty.easy,
    latitude: 46.948,
    nationalAnimal: 'Swiss Guard',
  ),
  Country(
    name: 'Kosovo',
    flagPath: 'assets/flags/euflags/kosovo_flag.png',
    capital: 'Pristina',
    difficulty: Difficulty.easy,
    latitude: 42.662,
    nationalAnimal: 'Golden eagle',
  ),
];

List<Country> asianCountries = [
  Country(
    name: 'Afghanistan',
    flagPath: 'assets/flags/afghanistan_flag.png',
    capital: 'Kabul',
    difficulty: Difficulty.easy,
    latitude: 33.939,
    nationalAnimal: 'Snow leopard',
  ),
  Country(
    name: 'Armenia',
    flagPath: 'assets/flags/armenia_flag.png',
    capital: 'Yerevan',
    difficulty: Difficulty.easy,
    latitude: 40.187,
    nationalAnimal: 'Eagle',
  ),
  Country(
    name: 'Azerbaijan',
    flagPath: 'assets/flags/azerbaijan_flag.png',
    capital: 'Baku',
    difficulty: Difficulty.easy,
    latitude: 40.409,
    nationalAnimal: 'Karabakh horse',
  ),
  Country(
    name: 'Bahrain',
    flagPath: 'assets/flags/bahrain_flag.png',
    capital: 'Manama',
    difficulty: Difficulty.easy,
    latitude: 26.066,
    nationalAnimal: 'Arabian oryx',
  ),
  Country(
    name: 'Bangladesh',
    flagPath: 'assets/flags/bangladesh_flag.png',
    capital: 'Dhaka',
    difficulty: Difficulty.easy,
    latitude: 23.810,
    nationalAnimal: 'Bengal tiger',
  ),
  Country(
    name: 'Bhutan',
    flagPath: 'assets/flags/bhutan_flag.png',
    capital: 'Thimphu',
    difficulty: Difficulty.easy,
    latitude: 27.471,
    nationalAnimal: 'Takin',
  ),
  Country(
    name: 'India',
    flagPath: 'assets/flags/india_flag.png',
    capital: 'New Delhi',
    difficulty: Difficulty.easy,
    latitude: 28.613,
    nationalAnimal: 'Bengal tiger',
  ),
  Country(
    name: 'Brunei',
    flagPath: 'assets/flags/brunei_flag.png',
    capital: 'Bandar Seri Begawan',
    difficulty: Difficulty.easy,
    latitude: 4.903,
    nationalAnimal: 'Proboscis monkey',
  ),
  Country(
    name: 'Cambodia',
    flagPath: 'assets/flags/cambodia_flag.png',
    capital: 'Phnom Penh',
    difficulty: Difficulty.easy,
    latitude: 11.556,
    nationalAnimal: 'Kouprey',
  ),
  Country(
    name: 'China',
    flagPath: 'assets/flags/china_flag.png',
    capital: 'Beijing',
    difficulty: Difficulty.easy,
    latitude: 39.904,
    nationalAnimal: 'Giant panda',
  ),
  Country(
    name: 'Cyprus',
    flagPath: 'assets/flags/cyprus_flag.png',
    capital: 'Nicosia',
    difficulty: Difficulty.easy,
    latitude: 35.126,
    nationalAnimal: 'Mouflon',
  ),
  Country(
    name: 'Georgia',
    flagPath: 'assets/flags/georgia_flag.png',
    capital: 'Tbilisi',
    difficulty: Difficulty.easy,
    latitude: 41.715,
    nationalAnimal: 'Bull',
  ),
  Country(
    name: 'Indonesia',
    flagPath: 'assets/flags/indonesia_flag.png',
    capital: 'Jakarta',
    difficulty: Difficulty.easy,
    latitude: -6.214,
    nationalAnimal: 'Komodo dragon',
  ),
  Country(
    name: 'Iran',
    flagPath: 'assets/flags/iran_flag.png',
    capital: 'Tehran',
    difficulty: Difficulty.easy,
    latitude: 35.689,
    nationalAnimal: 'Asiatic cheetah',
  ),
  Country(
    name: 'Iraq',
    flagPath: 'assets/flags/iraq_flag.png',
    capital: 'Baghdad',
    difficulty: Difficulty.easy,
    latitude: 33.315,
    nationalAnimal: 'Gazelle',
  ),
  Country(
    name: 'Israel',
    flagPath: 'assets/flags/israel_flag.png',
    capital: 'Jerusalem',
    difficulty: Difficulty.easy,
    latitude: 31.768,
    nationalAnimal: 'Israeli gazelle',
  ),
  Country(
    name: 'Japan',
    flagPath: 'assets/flags/japan_flag.png',
    capital: 'Tokyo',
    difficulty: Difficulty.easy,
    latitude: 35.689,
    nationalAnimal: 'Green pheasant',
  ),
  Country(
    name: 'Jordan',
    flagPath: 'assets/flags/jordan_flag.png',
    capital: 'Amman',
    difficulty: Difficulty.easy,
    latitude: 31.956,
    nationalAnimal: 'Arabian oryx',
  ),
  Country(
    name: 'Kazakhstan',
    flagPath: 'assets/flags/kazakhstan_flag.png',
    capital: 'Nur-Sultan',
    difficulty: Difficulty.easy,
    latitude: 51.169,
    nationalAnimal: 'Golden eagle',
  ),
  Country(
    name: 'North Korea',
    flagPath: 'assets/flags/north_korea_flag.png',
    capital: 'Pyongyang',
    difficulty: Difficulty.easy,
    latitude: 39.039,
    nationalAnimal: 'Chollima',
  ),
  Country(
    name: 'South Korea',
    flagPath: 'assets/flags/south_korea_flag.png',
    capital: 'Seoul',
    difficulty: Difficulty.easy,
    latitude: 37.566,
    nationalAnimal: 'Siberian tiger',
  ),
  Country(
    name: 'Kuwait',
    flagPath: 'assets/flags/kuwait_flag.png',
    capital: 'Kuwait City',
    difficulty: Difficulty.easy,
    latitude: 29.375,
    nationalAnimal: 'Arabian horse',
  ),
  Country(
    name: 'Kyrgyzstan',
    flagPath: 'assets/flags/kyrgyzstan_flag.png',
    capital: 'Bishkek',
    difficulty: Difficulty.easy,
    latitude: 42.874,
    nationalAnimal: 'Snow leopard',
  ),
  Country(
    name: 'Laos',
    flagPath: 'assets/flags/laos_flag.png',
    capital: 'Vientiane',
    difficulty: Difficulty.easy,
    latitude: 17.966,
    nationalAnimal: 'Elephant',
  ),
  Country(
    name: 'Lebanon',
    flagPath: 'assets/flags/lebanon_flag.png',
    capital: 'Beirut',
    difficulty: Difficulty.easy,
    latitude: 33.893,
    nationalAnimal: 'Striped hyena',
  ),
  Country(
    name: 'Macau',
    flagPath: 'assets/flags/macau_flag.png',
    capital: 'Macau',
    difficulty: Difficulty.easy,
    latitude: 22.198,
    nationalAnimal: 'Peregrine falcon',
  ),
  Country(
    name: 'Malaysia',
    flagPath: 'assets/flags/malaysia_flag.png',
    capital: 'Kuala Lumpur',
    difficulty: Difficulty.easy,
    latitude: 3.139,
    nationalAnimal: 'Malayan tiger',
  ),
  Country(
    name: 'Maldives',
    flagPath: 'assets/flags/maldives_flag.png',
    capital: 'Male',
    difficulty: Difficulty.easy,
    latitude: 4.175,
    nationalAnimal: 'Yellowfin tuna',
  ),
  Country(
    name: 'Mongolia',
    flagPath: 'assets/flags/mongolia_flag.png',
    capital: 'Ulaanbaatar',
    difficulty: Difficulty.easy,
    latitude: 47.886,
    nationalAnimal: 'Przewalski\'s horse',
  ),
  Country(
    name: 'Myanmar',
    flagPath: 'assets/flags/myanmar_flag.png',
    capital: 'Naypyidaw',
    difficulty: Difficulty.easy,
    latitude: 21.916,
    nationalAnimal: 'Burmese peacock',
  ),
  Country(
    name: 'Nepal',
    flagPath: 'assets/flags/nepal_flag.png',
    capital: 'Kathmandu',
    difficulty: Difficulty.easy,
    latitude: 27.717,
    nationalAnimal: 'Cow',
  ),
  Country(
    name: 'Pakistan',
    flagPath: 'assets/flags/pakistan_flag.png',
    capital: 'Islamabad',
    difficulty: Difficulty.easy,
    latitude: 30.375,
    nationalAnimal: 'Markhor',
  ),
  Country(
    name: 'Palestine',
    flagPath: 'assets/flags/palestine_flag.png',
    capital: 'Ramallah',
    difficulty: Difficulty.easy,
    latitude: 31.952,
    nationalAnimal: 'Gazelle',
  ),
  Country(
    name: 'Philippines',
    flagPath: 'assets/flags/philippines_flag.png',
    capital: 'Manila',
    difficulty: Difficulty.easy,
    latitude: 14.599,
    nationalAnimal: 'Carabao',
  ),
  Country(
    name: 'Qatar',
    flagPath: 'assets/flags/qatar_flag.png',
    capital: 'Doha',
    difficulty: Difficulty.easy,
    latitude: 25.285,
    nationalAnimal: 'Arabian oryx',
  ),
  Country(
    name: 'Saudi Arabia',
    flagPath: 'assets/flags/saudi_arabia_flag.png',
    capital: 'Riyadh',
    difficulty: Difficulty.easy,
    latitude: 24.713,
    nationalAnimal: 'Arabian camel',
  ),
  Country(
    name: 'Singapore',
    flagPath: 'assets/flags/singapore_flag.png',
    capital: 'Singapore',
    difficulty: Difficulty.easy,
    latitude: 1.352,
    nationalAnimal: 'Merlion',
  ),
  Country(
    name: 'Sri Lanka',
    flagPath: 'assets/flags/sri_lanka_flag.png',
    capital: 'Colombo',
    difficulty: Difficulty.easy,
    latitude: 6.927,
    nationalAnimal: 'Lion',
  ),
  Country(
    name: 'Syria',
    flagPath: 'assets/flags/syria_flag.png',
    capital: 'Damascus',
    difficulty: Difficulty.easy,
    latitude: 33.513,
    nationalAnimal: 'Arabian leopard',
  ),
  Country(
    name: 'Tajikistan',
    flagPath: 'assets/flags/tajikistan_flag.png',
    capital: 'Dushanbe',
    difficulty: Difficulty.easy,
    latitude: 38.861,
    nationalAnimal: 'Marco Polo sheep',
  ),
  Country(
    name: 'Thailand',
    flagPath: 'assets/flags/thailand_flag.png',
    capital: 'Bangkok',
    difficulty: Difficulty.easy,
    latitude: 13.756,
    nationalAnimal: 'Elephant',
  ),
  Country(
    name: 'East Timor',
    flagPath: 'assets/flags/east_timor_flag.png',
    capital: 'Dili',
    difficulty: Difficulty.easy,
    latitude: -8.556,
    nationalAnimal: 'Crocodile',
  ),
  Country(
    name: 'Turkey',
    flagPath: 'assets/flags/turkey_flag.png',
    capital: 'Ankara',
    difficulty: Difficulty.easy,
    latitude: 39.933,
    nationalAnimal: 'Gray wolf',
  ),
  Country(
    name: 'Turkmenistan',
    flagPath: 'assets/flags/turkmenistan_flag.png',
    capital: 'Ashgabat',
    difficulty: Difficulty.easy,
    latitude: 37.960,
    nationalAnimal: 'Akhal-Teke horse',
  ),
  Country(
    name: 'United Arab Emirates',
    flagPath: 'assets/flags/uae_flag.png',
    capital: 'Abu Dhabi',
    difficulty: Difficulty.easy,
    latitude: 24.453,
    nationalAnimal: 'Arabian oryx',
  ),
  Country(
    name: 'Uzbekistan',
    flagPath: 'assets/flags/uzbekistan_flag.png',
    capital: 'Tashkent',
    difficulty: Difficulty.easy,
    latitude: 41.377,
    nationalAnimal: 'Snow leopard',
  ),
  Country(
    name: 'Vietnam',
    flagPath: 'assets/flags/vietnam_flag.png',
    capital: 'Hanoi',
    difficulty: Difficulty.easy,
    latitude: 21.028,
    nationalAnimal: 'Water buffalo',
  ),
  Country(
    name: 'Yemen',
    flagPath: 'assets/flags/yemen_flag.png',
    capital: 'Sanaa',
    difficulty: Difficulty.easy,
    latitude: 15.369,
    nationalAnimal: 'Arabian leopard',
  ),
];
